# Generated by Django 4.2.1 on 2025-06-21 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_code', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='FİN kod yalnız böyük hərflər və rəqəmlərdən ibarət 7 simvol olmalıdır.', regex='^[A-Z0-9]{7}$')])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_prefix', models.CharField(choices=[('Aze1', '050'), ('Aze2', '051'), ('Aze3', '010'), ('Bak1', '055'), ('Bak2', '099'), ('Nar1', '070'), ('Nar2', '077')], default='Aze1', max_length=5)),
                ('phone_number', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Mobil nömrə 7 rəqəmli olmalıdır. Məs: 1234567', regex='^\\d{7}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
