# Generated by Django 4.2.1 on 2025-06-21 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0004_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='fin_code',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='FİN kod yalnız böyük hərflər və rəqəmlərdən ibarət 7 simvol olmalıdır.', regex='^[A-Z0-9]{7}$')]),
        ),
    ]
