# Generated by Django 4.2.1 on 2025-06-21 12:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0005_remove_patient_id_alter_patient_fin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(default=django.utils.timezone.now)),
                ('appointment_time', models.TimeField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist_app.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist_app.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist_app.service')),
            ],
        ),
    ]
