# Generated by Django 4.2.1 on 2025-06-21 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0006_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorEarnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist_app.doctor')),
            ],
        ),
    ]
