# Generated by Django 4.2.1 on 2025-06-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0007_doctorearnings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='doctor_type',
        ),
        migrations.AddField(
            model_name='service',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dentist_app.doctor'),
            preserve_default=False,
        ),
    ]
