# Generated by Django 4.2.1 on 2025-06-22 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0008_remove_service_doctor_type_service_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paid_amount',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='paid_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='qaime',
            field=models.FileField(default='/pdf/qaime.pdf', upload_to='pdf/'),
        ),
    ]
