# Generated by Django 4.2.1 on 2025-07-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0010_alter_appointment_id_alter_doctor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
