# Generated by Django 4.2.1 on 2025-07-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0013_appointmentsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
