# Generated by Django 4.2.1 on 2025-07-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0014_appointmentsession_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
